-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 12:00:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema microblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema microblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `microblog` DEFAULT CHARACTER SET utf8 ;
USE `microblog` ;

-- -----------------------------------------------------
-- Table `microblog`.`Traveler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Traveler` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(64) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`No_Existing_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`No_Existing_User` (
  `idtable1` INT NOT NULL,
  `Name` VARCHAR(64) NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Agent` (
  `idAgent` INT NOT NULL,
  `Name` VARCHAR(64) NULL,
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Post` (
  `idPost` INT NOT NULL,
  `Text` VARCHAR(1024) NULL,
  `Traveler_idUser` INT NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Flag` ENUM('inapropiate', 'approved', 'waiting') NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_Post_Traveler1_idx` (`Traveler_idUser` ASC),
  INDEX `fk_Post_Agent1_idx` (`Agent_idAgent` ASC),
  CONSTRAINT `fk_Post_Traveler1`
    FOREIGN KEY (`Traveler_idUser`)
    REFERENCES `microblog`.`Traveler` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Agent1`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `microblog`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Meta_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Meta_Tag` (
  `idMeta_Tag` INT NOT NULL,
  `Text` VARCHAR(64) NULL,
  `Flag` ENUM('approved', 'declined', 'waiting') NULL,
  `Agent_idAgent` INT NOT NULL,
  PRIMARY KEY (`idMeta_Tag`),
  INDEX `fk_Meta_Tag_Agent1_idx` (`Agent_idAgent` ASC),
  CONSTRAINT `fk_Meta_Tag_Agent1`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `microblog`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Experience` (
  `idExperience` INT NOT NULL,
  `Text` VARCHAR(64) NULL,
  PRIMARY KEY (`idExperience`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Post_Meta_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Post_Meta_Tag` (
  `Post_idPost` INT NOT NULL,
  `Meta_Tag_idMeta_Tag` INT NOT NULL,
  PRIMARY KEY (`Post_idPost`, `Meta_Tag_idMeta_Tag`),
  INDEX `fk_Post_has_Meta_Tag_Meta_Tag1_idx` (`Meta_Tag_idMeta_Tag` ASC),
  INDEX `fk_Post_has_Meta_Tag_Post_idx` (`Post_idPost` ASC),
  CONSTRAINT `fk_Post_has_Meta_Tag_Post`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `microblog`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_Meta_Tag_Meta_Tag1`
    FOREIGN KEY (`Meta_Tag_idMeta_Tag`)
    REFERENCES `microblog`.`Meta_Tag` (`idMeta_Tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Post_Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Post_Experience` (
  `Post_idPost` INT NOT NULL,
  `Experience_idExperience` INT NOT NULL,
  PRIMARY KEY (`Post_idPost`, `Experience_idExperience`),
  INDEX `fk_Post_has_Experience_Experience1_idx` (`Experience_idExperience` ASC),
  INDEX `fk_Post_has_Experience_Post1_idx` (`Post_idPost` ASC),
  CONSTRAINT `fk_Post_has_Experience_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `microblog`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_Experience_Experience1`
    FOREIGN KEY (`Experience_idExperience`)
    REFERENCES `microblog`.`Experience` (`idExperience`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Post_No_Existing_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Post_No_Existing_User` (
  `Post_idPost` INT NOT NULL,
  `No_Existing_User_idtable1` INT NOT NULL,
  PRIMARY KEY (`Post_idPost`, `No_Existing_User_idtable1`),
  INDEX `fk_Post_has_No_Existing_User_No_Existing_User1_idx` (`No_Existing_User_idtable1` ASC),
  INDEX `fk_Post_has_No_Existing_User_Post1_idx` (`Post_idPost` ASC),
  CONSTRAINT `fk_Post_has_No_Existing_User_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `microblog`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_No_Existing_User_No_Existing_User1`
    FOREIGN KEY (`No_Existing_User_idtable1`)
    REFERENCES `microblog`.`No_Existing_User` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microblog`.`Post_Traveler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microblog`.`Post_Traveler` (
  `Post_idPost` INT NOT NULL,
  `Traveler_idUser` INT NOT NULL,
  PRIMARY KEY (`Post_idPost`, `Traveler_idUser`),
  INDEX `fk_Post_has_Traveler_Traveler1_idx` (`Traveler_idUser` ASC),
  INDEX `fk_Post_has_Traveler_Post1_idx` (`Post_idPost` ASC),
  CONSTRAINT `fk_Post_has_Traveler_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `microblog`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_Traveler_Traveler1`
    FOREIGN KEY (`Traveler_idUser`)
    REFERENCES `microblog`.`Traveler` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
